#Using https://github.com/marketplace/actions/deploy-to-neocities 

name: Deploy to neocities

on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Ruby
          uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
          with:
            ruby-version: '3.1' # Not needed with a .ruby-version file
            bundler-cache: true # runs 'bundle install' and caches installed gems automatically
            cache-version: 0 # Increment this number if you need to re-download cached gems
        - name: Build with Jekyll
        # Outputs to the './_site' directory by default
          run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
          env:
            JEKYLL_ENV: production
        - name: Deploy to neocities
          uses: bcomnes/deploy-to-neocities@v2
          with:
            api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
            cleanup: false
            dist_dir: _site
